#!/bin/bash
# namespaced as: JBASH_FORMAT_

JBASH_FORMAT_separator="==============================================================================="
JBASH_FORMAT_line_start="# "

JBASH_FORMAT_color_prefix="\033"
JBASH_FORMAT_color_reset="$JBASH_FORMAT_color_prefix[0m"

JBASH_FORMAT_line () { echo -e "$JBASH_FORMAT_line_start$2"; }
JBASH_FORMAT_nline () { echo -en "$JBASH_FORMAT_line_start$2"; }

JBASH_FORMAT_cline () { echo -e "$JBASH_FORMAT_color_prefix[${1}m$JBASH_FORMAT_line_start$2$JBASH_FORMAT_color_reset"; }
JBASH_FORMAT_cnline () { echo -en "$JBASH_FORMAT_color_prefix[${1}m$JBASH_FORMAT_line_start$2$JBASH_FORMAT_color_reset"; }

JBASH_FORMAT_endslash () {
	str=$1
	if [ -z "$str" ]; then echo ""; return; fi
	if [ "${str:0:1}" = "/" ]; then str="${str:1:${#str}}"; fi
	if [ -n "$str" ] && [ "${str:${#str}-1}" != "/" ]; then str="$str/"; fi
	echo "$str"
}
