#!/bin/bash
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/jbash/common
JBASH_begin

basedir=$1
if [ -z "$basedir" ]; then basedir="."; fi
JBASH_IO_ask "Ready to set up in '$basedir' proceed? [y/N]"
read response
if ! JBASH_IO_saidyes $response; then
	JBASH_IO_note "quitting"
	JBASH_quit 0
fi

JBASH_IO_info "creating directories ..."
dirs=( public public/assets public/assets/css public/assets/img public/assets/js script script/lib script/pages script/headers script/footers script/partials )
for d in "${dirs[@]}"; do
	dir="$basedir/$d"
	if [ -d "$dir" ]; then
		JBASH_IO_note "directory already exists: $dir"
		continue
	fi
	JBASH_IO_code "mkdir $dir"
	dirstatus=$( mkdir $dir )
	if [ -n "$dirstatus" ]; then JBASH_IO_error "$dirstatus"
	else JBASH_IO_ok "$d created"; fi
done

JBASH_IO_info "copying templated files ..."
declare -A files
files[".htaccess"]="public/"
files["index.php"]="public/"
files["setup.php"]=""
htaccess_copied=false
setup_copied=false
for filename in "${!files[@]}"; do
	srcfile="$DIR/templates/$filename"
	outfile="$basedir/${files[$filename]}$filename"
	if [ -f "$outfile" ]; then
		JBASH_IO_note "file already exists: $outfile"
		continue
	fi
	JBASH_IO_code "cp $srcfile $outfile"
	cpstatus=$( cp $srcfile $outfile )
	if [ -n "$cpstatus" ]; then JBASH_IO_error "$cpstatus";
	else
		JBASH_IO_ok "$outfile copied"
		if [ "$filename" = "setup.php" ]; then setup_copied=true; fi
		if [ "$filename" = ".htaccess" ]; then htaccess_copied=true; fi
	fi
done

setting_url=""

if $setup_copied; then
	JBASH_IO_info "writing some settings ..."
	setup_file="$basedir/setup.php"
	JBASH_IO_ask "MySQL Host"
	read setting_mysql_host
	JBASH_IO_ask "MySQL Username"
	read setting_mysql_user
	JBASH_IO_ask "MySQL Password"
	read setting_mysql_pass
	JBASH_IO_ask "MySQL Database"
	read setting_mysql_db
	JBASH_IO_ask "Domain Base"
	read setting_url
	JBASH_IO_ask "URL Prefix"
	read setting_url_sub
	setting_url=$(JBASH_FORMAT_endslash $setting_url)
	JBASH_IO_ask "Timezone"
	read setting_timezone
	sed -i.bak "s#__MYSQL_HOST__#$setting_mysql_host#" "$setup_file"
	sed -i.bak "s/__MYSQL_USER__/$setting_mysql_user/" "$setup_file"
	sed -i.bak "s/__MYSQL_PASS__/$setting_mysql_pass/" "$setup_file"
	sed -i.bak "s#__MYSQL_DB__#$setting_mysql_db#" "$setup_file"
	sed -i.bak "s#__PATH_URL__#$setting_url#" "$setup_file"
	sed -i.bak "s#__PATH_URL_SUB__#$setting_url_sub#" "$setup_file"
	sed -i.bak "s#__TIMEZONE__#$setting_timezone#" "$setup_file"
	rm "${setup_file}.bak"
fi

if $htaccess_copied; then
	JBASH_IO_info "writing htaccess ..."
	htaccess_file="$basedir/public/.htaccess"
	if ! $setup_copied; then
		JBASH_IO_ask "URL Prefix"
		read setting_url
		setting_url=$(JBASH_FORMAT_endslash $setting_url)
	fi
	sed -i.bak "s#__PATH_URL__#$setting_url#" "$htaccess_file"
	rm "${htaccess_file}.bak"
fi

JBASH_IO_info "checking packages ..."
packages=( mysql-server mysql-client apache2 php5 php5-cli php5-mysql libapache2-mod-php5 )
for package in "${packages[@]}"; do
	linecount=$(dpkg -l | grep -E "^ii" | grep " $package " | wc -l)
	if [ "$linecount" = "0" ]; then JBASH_IO_error "missing package: $package";
	else JBASH_IO_ok "package found: $package"; fi
done

JBASH_end
